#!/usr/bin/perl
# radiod
# TODO => -playlist, parse log OR > fifo_out
use Radiod::URI qw(listchans);
$APP     = 'radiod';
$VERSION = 0.1;
use strict;
use Radiod::URI qw(geturi);
use App::Daemon qw(daemonize);

my $cmd = 'mplayer -cache 200 -quiet -identify';
my $cmdOpts = '-slave -input file=$HOME/.mplayer/radiod.fifo';
my $log = '$HOME/.mplayer/radiod.log';

if(-p "$ENV{HOME}/.mplayer/radiod.fifo") {
  print "FIFO found - all good.\n\n";
}
else {
  require POSIX;
  POSIX::mkfifo("$ENV{HOME}/.mplayer/radiod.fifo", 0666)
    or die "Can not make fifo: $ENV{HOME}/.mplayer/fifo: $!";
}

listchans();
print "\nStation: ";
my $choice = <STDIN>; chomp($choice);

my $loadStation = geturi($choice);
die("No such channel") unless $loadStation;

print << "NOTE";
Daemonizing, bye...

If you want me something, you can give me commands through
the named pipe.
NOTE

daemonize();
system("$cmd $cmdOpts $loadStation > $log") == 0 or die;
