#!/usr/bin/perl

our $APP     = 'RPD';
our $VERSION = 0.3;

=rpd
  Radio Playing Daemon

  A daemon for playing radio streams

=cut

use strict;
use Radiod::URI qw(geturi listchans);
use Working::Daemon;

my $chan = shift;

my $log      = "$ENV{HOME}/.mplayer/rpd.log";
my $fifo     = "$ENV{HOME}/.mplayer/rpd.fifo";
my $pidfile  = '/tmp/rpd.pid';
my $append   = 0;
my $cmd      = 'mplayer -cache 400 -identify -idle ';
my $cmd_opt  = "-slave -input file=$fifo";
my $chan_url = undef;

if(!-p $fifo) {
  require POSIX;
  POSIX::mkfifo($fifo, 0666) or die "Cant mkfifo $fifo: $!";
}

if($chan eq '-l' or $chan eq '--list') {
  listchans();
  exit 0;
}

if(defined(geturi($chan))) {
  $chan_url = geturi($chan);
  play($chan_url);
}
else {
  if(!$chan) { # no args
    usage();
  }
  else { # arg is invalid
    # We have already shifted of a value from @ARGV
    printf("Invalid argument%s\n",  (@ARGV > 0) ? 's' : '');
  }
}

sub play {
  my $station = shift;
  croak("Provide a station") unless $station;
  daemonize();
  if($append != 0) {
    system("$cmd $cmd_opt $chan_url &>> $log");
  }
  else {
    system("$cmd $cmd_opt $chan_url &> $log");
  }
}

sub usage {
  print << "USAGE";
  $APP $VERSION
  Usage: rpd [OPTIONS] (STATION)

  OPTIONS
    -l, --list     list channels


USAGE
}

sub daemonize {
  open(my $pid, '>', $pidfile) or croak("Cant create pidfile $pidfile");
  print $pid $$;
  close($pid);

  my $daemon = Working::Daemon->new;
  $daemon->name('Radio Playing Daemon');
  $daemon->do_action;
}
