#!/usr/bin/perl

$APP     = 'RPD';
$VERSION = 0.1;

=rpd
  Radio Playing Daemon

  A daemon for playing radio streams

=cut


use strict;
use Radiod::URI qw(geturi listchans);
use Working::Daemon;

my $fifo    = "$ENV{HOME}/.mplayer/rpd.fifo";
my $append  = 1; # if non-zero, RPD will append to an existing log
my $cmd     = 'mplayer -cache 400 -identify -idle ';
my $cmdOpts = "-slave -input file=$fifo";
my $log     = "$ENV{HOME}/.mplayer/rpd.log";

if(-p $fifo) {
  print "FIFO found - all good.\n\n";
}
else {
  require POSIX;
  POSIX::mkfifo($fifo, 0666)
    or die "Can not make fifo: $fifo $!";
}

listchans();
print "\nStation: ";
chomp(my $choice = <STDIN>);

my $loadStation = geturi($choice) // geturi('dingata'); # default


daemonize();

if($append != 0) {
  system("$cmd $cmdOpts $loadStation &>> $log") == 0 or die;
}
else {
  system("$cmd $cmdOpts $loadStation &> $log") == 0 or die; 
}

sub daemonize {
  my $daemon = Working::Daemon->new;
  $daemon->name('radiod');
  $daemon->do_action;
}
