#!/usr/bin/perl
use strict;
use LWP::Simple;
use XML::Simple;
use Data::Dumper;

my $xml = XMLin(get("http://api.sr.se/api/channels/channels.aspx"));
$xml = $xml->{channel};
my $npurl = "http://api.sr.se/api/rightnowinfo/Rightnowinfo.aspx?unit=";
foreach my $chname(sort(keys(%{$xml}))) {
  my $id = $xml->{$chname}->{id}; 
  my $xml2 = XMLin(get("$npurl$id"));
  my $title = $xml2->{Channel}->{SongTitle};
  my $artist = $xml2->{Channel}->{Artist};
  my $nowplaying = sprintf(
    "\033[38;5;102m%s\033[0m by \033[38;5;105m%s\033[0m", $title, $artist);
  if(ref($artist or $title)) {
    $nowplaying = "";
  }

  printf("%5d \033[38;5;100m%20s\033[0m %s\n",
    $id, $chname, $nowplaying);
}
